# https://docs.docker.com/compose/compose-file/compose-file-v3/
version: "3.9"

services:
  webapp:
    container_name: catalytic-webapp
    image: "tylerlwsmith/catalytic-webapp:${BUILD_TAG:-latest}"
    restart: always
    env_file: ${ENV_FILE:-.env}
    environment:
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: 1
    expose:
      - "9000"

  webserver:
    container_name: catalytic-webserver
    image: "tylerlwsmith/catalytic-webserver:${BUILD_TAG:-latest}"
    restart: always
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "8080:8080"

  database:
    container_name: catalytic-database
    image: postgres:13
    restart: always
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-5432}:5432"
    expose:
      - "${DB_PORT:-5432}"
    environment:
      POSTGRES_DB: "${DB_DATABASE}"
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"

volumes:
  database:
